version: "3.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

services:
  xmrig:
    container_name: xmrig
    build: ./
    restart: on-failure
    logging: *default-logging
